small changes

diff --git a/errors_resolver_demo b/errors_resolver_demo
--- a/errors_resolver_demo
+++ b/errors_resolver_demo
@@ -34,6 +34,12 @@ showv()
 	val=$(eval "echo \$${1}"); echo -n "$1='$val' $2"
 }
 
+fatal()
+{
+	echo "Fatal error $1"
+	exit 1
+}
+
 echo -e "Initial invironment\n"
 showv CC $'\n'
 showv includedir $'\n'
@@ -55,9 +61,10 @@ echo
 echo -e "pass 3: resolve library paths\n"
 eval "$(make -B -f /dev/null errors_resolver_sample 2>&1 | ./errors_resolver.py 2> /dev/null | tee out.tmp)"
 cat out.tmp
+echo
 
-echo -e "\nFinal compilation:\n"
-make -B -f /dev/null errors_resolver_sample
+echo -e "Final compilation:\n"
+make -B -f /dev/null errors_resolver_sample || fatal
 
 if [ -e ./errors_resolver_sample ]; then
 	arch=$(echo $(file -e elf ./errors_resolver_sample | cut -d',' -f2 | tr - _))
